name: Scrape and Upload Dataset to W&B

on:
  workflow_dispatch:

jobs:
  scrape-and-upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run image scraper
      run: python scraper/duckduckgo.py

    - name: Upload dataset to Weights & Biases
      env:
        WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}
      run: python scripts/upload.py